#!/bin/sh

#set -euo pipefail
set -eu

backlight_path="/sys/class/backlight/ideapad"

[ -d "$backlight_path" ] || { printf '󰃞 N/A\n'; exit 0; }

read -r curr_brightness < "$backlight_path/brightness"
read -r max_brightness < "$backlight_path/max_brightness"

[ "$max_brightness" -gt 0 ] || { printf '󰃞 N/A\n'; exit 0; }

if [ "$curr_brightness" -le 0 ]; then
  icon="󰃞"
elif [ "$curr_brightness" -lt $((max_brightness * 3 / 10)) ]; then
  icon="󰃟"
elif [ "$curr_brightness" -lt $((max_brightness * 7 / 10)) ]; then
  icon="󰃝"
else
  icon="󰃠"
fi

printf '%s %d\n' "$icon" "$curr_brightness"
#printf '%s %d/%d\n' "$icon" "$curr_brightness" "$max_brightness"
