#!/bin/sh

#set -euo pipefail
set -eu

mem_total=0
mem_avail=0

while read -r key value _; do
  case "$key" in
    MemTotal:)     mem_total=$value ;;
    MemAvailable:) mem_avail=$value ;;
  esac
  if [ "$mem_total" -gt 0 ] && [ "$mem_avail" -gt 0 ]; then
    break
  fi
done < /proc/meminfo

mem_used=$((mem_total - mem_avail))

total_gb_scaled=$(( (mem_total * 10) / 1024 / 1024 ))
used_gb_scaled=$(( (mem_used * 10) / 1024 / 1024 ))

total_int=$((total_gb_scaled / 10))
total_dec=$((total_gb_scaled % 10))

used_int=$((used_gb_scaled / 10))
used_dec=$((used_gb_scaled % 10))

#percent_used=$(( (mem_used * 100) / mem_total ))

#if [ "$percent_used" -ge 85 ]; then
#  icon="󰓅"
#else
#  icon=""
#fi

icon=""

printf '%s %d.%dG/%d.%dG\n' "$icon" "$used_int" "$used_dec" "$total_int" "$total_dec"

#printf '%s %d%%\n' "$icon" "$percent_used"
