#!/bin/sh

#set -euo pipefail
set -eu

tries=1
max_tries=5

# prevent the first launch of the script not showing anything if the audio controller is not yet loaded
while [ "$tries" -le "$max_tries" ]; do
  raw_vol=$(/run/current-system/sw/bin/wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null || true)
  if [ -n "$raw_vol" ]; then
    break
  fi
  tries=$((tries + 1))
  sleep 0.2
done

case "$raw_vol" in
  *\[MUTED\]*)
    printf '󰝟 MUTE\n'
    exit 0
  ;;
esac

val="${raw_vol#Volume: }"
set -- ${val%.*} ${val#*.}

if [ "$1" -eq 1 ]; then
  volume=100
else
  volume=$((1$2 - 100))
fi

if [ "$volume" -eq 0 ]; then
  icon="󰝟"
elif [ "$volume" -lt 30 ]; then
  icon=""
elif [ "$volume" -lt 70 ]; then
  icon=""
else
  icon=""
fi

printf '%s %d%%\n' "$icon" "$volume"
