#!/bin/sh

#set -euo pipefail
set -eu

tries=1
max_tries=5

# prevent the first launch of the script not showing anything if the audio controller is not yet loaded
while [ "$tries" -le "$max_tries" ]; do
  raw_info=$(/run/current-system/sw/bin/amixer sget Master 2>/dev/null || true)
  if [ -n "$raw_info" ]; then
    break
  fi
  tries=$((tries + 1))
  sleep 0.2
done

if [ -z "$raw_info" ]; then
  printf '󰖁 N/A\n'
  exit 0
fi

case "$raw_info" in
  *\[off\]*)
    printf '󰝟 MUTE\n'
    exit 0
  ;;
esac

val="${raw_info#*\[}"
volume="${val%%\%]*}"

volume="${volume:-0}"

if [ "$volume" -eq 0 ]; then
  icon="󰝟"
elif [ "$volume" -lt 30 ]; then
  icon=""
elif [ "$volume" -lt 70 ]; then
  icon=""
else
  icon=""
fi

printf '%s %d%%\n' "$icon" "$volume"
