#!/bin/sh

set -euo pipefail

if ! raw_vol=$(/run/current-system/sw/bin/wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null); then
  printf '󰖁 N/A\n'
  exit 0
fi

case "$raw_vol" in
  *\[MUTED\]*)
    printf '󰝟 MUTE\n'
    exit 0
  ;;
esac

val="${raw_vol#Volume: }"
set -- ${val%.*} ${val#*.}
if [ "$1" -eq 1 ]; then
  volume=100
else
  volume=$((1$2 - 100))
fi

if [ "$volume" -eq 0 ]; then
  icon="󰝟"
elif [ "$volume" -lt 30 ]; then
  icon=""
elif [ "$volume" -lt 70 ]; then
  icon=""
else
  icon=""
fi

printf '%s %d%%\n' "$icon" "$volume"
